# Generated by Django 4.2.16 on 2024-09-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('room_number', models.CharField(max_length=10)),
                ('pass_photo', models.ImageField(upload_to='pass_photos/')),
                ('is_verified', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('telegram_id', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
